import { 
  Contest,
  ContestPlatform,
  Status,
} from "@/types";

export const contests: Contest[] = [
  {
      id: "START175",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 175 (Rated till 5 stars)",
      status: Status.COMPLETED,
      startTime: "26 Feb 2025, 8:00 pm",
      endTime: "26 Feb 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START175",
      ytVideoURL: "https://www.youtube.com/watch?v=gPQyc5VRZ3c"
  },
  {
      id: "START176",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 176 (Rated till 4 star)",
      status: Status.COMPLETED,
      startTime: "5 Mar 2025, 8:00 pm",
      endTime: "5 Mar 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START176",
      ytVideoURL: "https://www.youtube.com/watch?v=Lbs_bhPeFRk"
  },
  {
      id: "START177",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 177 (Rated till 5 star)",
      status: Status.COMPLETED,
      startTime: "12 Mar 2025, 8:00 pm",
      endTime: "12 Mar 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START177",
      ytVideoURL: "https://www.youtube.com/watch?v=MKWQFDO5AqU"
  },
  {
      id: "START178",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 178 (Rated till 6 star)",
      status: Status.COMPLETED,
      startTime: "19 Mar 2025, 8:00 pm",
      endTime: "19 Mar 2025, 10:15 pm",
      durationTime: 135,
      url: "https://www.codechef.com/START178",
      ytVideoURL: "https://www.youtube.com/watch?v=wd9VWj7ORbI"
  },
  {
      id: "Weekly Contest 442",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 442",
      status: Status.COMPLETED,
      startTime: "23 Mar 2025, 8:00 am",
      endTime: "23 Mar 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-442",
      ytVideoURL: "https://www.youtube.com/watch?v=2irkmT9AUkM"
  },
  {
      id: "START179",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 179 (Rated till 5 star)",
      status: Status.COMPLETED,
      startTime: "26 Mar 2025, 8:00 pm",
      endTime: "26 Mar 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START179",
      ytVideoURL: "https://www.youtube.com/watch?v=Ho-hQytvKzU"
  },
  {
      id: "Biweekly Contest 153",
      platform: ContestPlatform.LEETCODE,
      name: "Biweekly Contest 153",
      status: Status.COMPLETED,
      startTime: "29 Mar 2025, 8:00 pm",
      endTime: "29 Mar 2025, 9:30 pm",
      durationTime: 90,
      url: "https://leetcode.com/contest/biweekly-contest-153"
  },
  {
      id: "Weekly Contest 443",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 443",
      status: Status.COMPLETED,
      startTime: "30 Mar 2025, 8:00 am",
      endTime: "30 Mar 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-443",
      ytVideoURL: "https://www.youtube.com/watch?v=ew_zmRf-jQ0"
  },
  {
      id: "START180",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 180 (Rated till 6 star)",
      status: Status.COMPLETED,
      startTime: "2 Apr 2025, 8:00 pm",
      endTime: "2 Apr 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START180",
      ytVideoURL: "https://www.youtube.com/watch?v=dQ17KfaiBEU"
  },
  {
      id: "Weekly Contest 444",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 444",
      status: Status.COMPLETED,
      startTime: "6 Apr 2025, 8:00 am",
      endTime: "6 Apr 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-444",
      ytVideoURL: "https://www.youtube.com/watch?v=FtAOJaEpzIo"
  },
  {
      id: "START181",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 181 (Rated for all)",
      status: Status.COMPLETED,
      startTime: "9 Apr 2025, 8:00 pm",
      endTime: "9 Apr 2025, 10:30 pm",
      durationTime: 150,
      url: "https://www.codechef.com/START181",
      ytVideoURL: "https://www.youtube.com/watch?v=3ws4jYEgn0A"
  },
  {
      id: "Biweekly Contest 154",
      platform: ContestPlatform.LEETCODE,
      name: "Biweekly Contest 154",
      status: Status.COMPLETED,
      startTime: "12 Apr 2025, 8:00 pm",
      endTime: "12 Apr 2025, 9:30 pm",
      durationTime: 90,
      url: "https://leetcode.com/contest/biweekly-contest-154",
      ytVideoURL: "https://www.youtube.com/watch?v=ZZHKIHJihGI"
  },
  {
      id: "Weekly Contest 445",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 445",
      status: Status.COMPLETED,
      startTime: "13 Apr 2025, 8:00 am",
      endTime: "13 Apr 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-445",
      ytVideoURL: "https://www.youtube.com/watch?v=ETla482jln4"
  },
  {
      id: "2094",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1017 (Div. 4)",
      status: Status.COMPLETED,
      startTime: "13 Apr 2025, 9:05 pm",
      endTime: "13 Apr 2025, 11:20 pm",
      durationTime: 135,
      url: "https://codeforces.com/contest/2094",
      ytVideoURL: "https://www.youtube.com/watch?v=4TPSNO4Gihw"
  },
  {
      id: "START182",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 182 (Rated till 5 star)",
      status: Status.COMPLETED,
      startTime: "16 Apr 2025, 8:00 pm",
      endTime: "16 Apr 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START182",
      ytVideoURL: "https://www.youtube.com/watch?v=Xh2gHFLZnkI"
  },
  {
      id: "2096",
      platform: ContestPlatform.CODEFORCES,
      name: "Neowise Labs Contest 1 (Codeforces Round 1018, Div. 1 + Div. 2)",
      status: Status.COMPLETED,
      startTime: "19 Apr 2025, 8:05 pm",
      endTime: "19 Apr 2025, 10:05 pm",
      durationTime: 120,
      url: "https://codeforces.com/contest/2096"
  },
  {
      id: "Weekly Contest 446",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 446",
      status: Status.COMPLETED,
      startTime: "20 Apr 2025, 8:00 am",
      endTime: "20 Apr 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-446",
      ytVideoURL: "https://www.youtube.com/watch?v=Z1NhMfwyciw"
  },
  {
      id: "2105",
      platform: ContestPlatform.CODEFORCES,
      name: "Tact Smart Battle 1",
      status: Status.COMPLETED,
      startTime: "21 Apr 2025, 2:30 pm",
      endTime: "28 Apr 2025, 2:30 pm",
      durationTime: 10080,
      url: "https://codeforces.com/contest/2105"
  },
  {
      id: "2103",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1019 (Div. 2)",
      status: Status.COMPLETED,
      startTime: "21 Apr 2025, 8:05 pm",
      endTime: "21 Apr 2025, 10:05 pm",
      durationTime: 120,
      url: "https://codeforces.com/contest/2103",
      ytVideoURL: "https://www.youtube.com/watch?v=iSS2J8qkI5E"
  },
  {
      id: "START183",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 183 (Rated till 6 star)",
      status: Status.COMPLETED,
      startTime: "23 Apr 2025, 8:00 pm",
      endTime: "23 Apr 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START183",
      ytVideoURL: "https://www.youtube.com/watch?v=Wyv9XWwJFr8"
  },
  {
      id: "2106",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1020 (Div. 3)",
      status: Status.COMPLETED,
      startTime: "24 Apr 2025, 8:05 pm",
      endTime: "24 Apr 2025, 10:20 pm",
      durationTime: 135,
      url: "https://codeforces.com/contest/2106",
      ytVideoURL: "https://www.youtube.com/watch?v=6KopfM-IsvI"
  },
  {
      id: "2097",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1021 (Div. 1)",
      status: Status.COMPLETED,
      startTime: "26 Apr 2025, 2:05 pm",
      endTime: "26 Apr 2025, 5:05 pm",
      durationTime: 180,
      url: "https://codeforces.com/contest/2097",
      ytVideoURL: "https://www.youtube.com/watch?v=6tVfyy4M8MQ"
  },
  {
      id: "2098",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1021 (Div. 2)",
      status: Status.COMPLETED,
      startTime: "26 Apr 2025, 2:05 pm",
      endTime: "26 Apr 2025, 5:05 pm",
      durationTime: 180,
      url: "https://codeforces.com/contest/2098",
      ytVideoURL: "https://www.youtube.com/watch?v=6tVfyy4M8MQ"
  },
  {
      id: "Biweekly Contest 155",
      platform: ContestPlatform.LEETCODE,
      name: "Biweekly Contest 155",
      status: Status.COMPLETED,
      startTime: "26 Apr 2025, 8:00 pm",
      endTime: "26 Apr 2025, 9:30 pm",
      durationTime: 90,
      url: "https://leetcode.com/contest/biweekly-contest-155",
      ytVideoURL: "https://www.youtube.com/watch?v=oqSIMuUjWNA"
  },
  {
      id: "Weekly Contest 447",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 447",
      status: Status.COMPLETED,
      startTime: "27 Apr 2025, 8:00 am",
      endTime: "27 Apr 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-447",
      ytVideoURL: "https://www.youtube.com/watch?v=Lk-yUVNcfR4"
  },
  {
      id: "2104",
      platform: ContestPlatform.CODEFORCES,
      name: "Educational Codeforces Round 178 (Rated for Div. 2)",
      status: Status.COMPLETED,
      startTime: "28 Apr 2025, 8:05 pm",
      endTime: "28 Apr 2025, 10:05 pm",
      durationTime: 120,
      url: "https://codeforces.com/contest/2104",
      ytVideoURL: "https://www.youtube.com/watch?v=mLrspzTTqrM"
  },
  {
      id: "START184",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 184 (Rated till 5 star)",
      status: Status.COMPLETED,
      startTime: "30 Apr 2025, 8:00 pm",
      endTime: "30 Apr 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START184",
      ytVideoURL: "https://www.youtube.com/watch?v=Izp9ncbL3hM"
  },
  {
      id: "2108",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1022 (Div. 2)",
      status: Status.COMPLETED,
      startTime: "1 May 2025, 8:05 pm",
      endTime: "1 May 2025, 10:05 pm",
      durationTime: 120,
      url: "https://codeforces.com/contest/2108",
      ytVideoURL: "https://www.youtube.com/watch?v=RiX-S_XQ5DA"
  },
  {
      id: "Weekly Contest 448",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 448",
      status: Status.COMPLETED,
      startTime: "4 May 2025, 8:00 am",
      endTime: "4 May 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-448",
      ytVideoURL: "https://www.youtube.com/watch?v=kAn4ty_MDb8"
  },
  {
      id: "2107",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1023 (Div. 2)",
      status: Status.COMPLETED,
      startTime: "5 May 2025, 8:05 pm",
      endTime: "5 May 2025, 10:20 pm",
      durationTime: 135,
      url: "https://codeforces.com/contest/2107",
      ytVideoURL: "https://www.youtube.com/watch?v=SlREu5xzV_o"
  },
  {
      id: "START185",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 185 (Rated till 5 star)",
      status: Status.ONGOING,
      startTime: "7 May 2025, 8:00 pm",
      endTime: "7 May 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START185"
  },
  {
      id: "Biweekly Contest 156",
      platform: ContestPlatform.LEETCODE,
      name: "Biweekly Contest 156",
      status: Status.UPCOMING,
      startTime: "10 May 2025, 8:00 pm",
      endTime: "10 May 2025, 9:30 pm",
      durationTime: 90,
      url: "https://leetcode.com/contest/biweekly-contest-156"
  },
  {
      id: "Weekly Contest 449",
      platform: ContestPlatform.LEETCODE,
      name: "Weekly Contest 449",
      status: Status.UPCOMING,
      startTime: "11 May 2025, 8:00 am",
      endTime: "11 May 2025, 9:30 am",
      durationTime: 90,
      url: "https://leetcode.com/contest/weekly-contest-449"
  },
  {
      id: "2101",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1024 (Div. 1)",
      status: Status.UPCOMING,
      startTime: "11 May 2025, 8:05 pm",
      endTime: "11 May 2025, 10:35 pm",
      durationTime: 150,
      url: "https://codeforces.com/contestRegistration/2101"
  },
  {
      id: "2102",
      platform: ContestPlatform.CODEFORCES,
      name: "Codeforces Round 1024 (Div. 2)",
      status: Status.UPCOMING,
      startTime: "11 May 2025, 8:05 pm",
      endTime: "11 May 2025, 10:35 pm",
      durationTime: 150,
      url: "https://codeforces.com/contestRegistration/2102"
  },
  {
      id: "START186",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 186",
      status: Status.UPCOMING,
      startTime: "14 May 2025, 8:00 pm",
      endTime: "14 May 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START186"
  },
  {
      id: "START187",
      platform: ContestPlatform.CODECHEF,
      name: "Starters 187",
      status: Status.UPCOMING,
      startTime: "21 May 2025, 8:00 pm",
      endTime: "21 May 2025, 10:00 pm",
      durationTime: 120,
      url: "https://www.codechef.com/START187"
  }
]